### ISSUE TITLE
CSSPool + Exclude Error

### ISSUE THREAD

**Issue by philipithomas** [stereobooster/jekyll-press#13]
I'm getting a CSSPool error that I can't fix with even the exclude property

From what I can tell, it seems to be due to having multiple @media max-widths in [my css file](https://github.com/philipithomas/www.philipithomas.com/blob/master/css/styles.css)
![Screen Shot 2013-02-14 at 10 49 13 PM](https://f.cloud.github.com/assets/1312414/159496/294b8084-772b-11e2-98a4-5882aac7362c.png)

**Comment by stereobooster** [comment]
project is deprecated https://github.com/stereobooster/jekyll-press/issues/35
