### ISSUE TITLE
Ignore by file path, not just file name.

### ISSUE THREAD

**Issue by davidwparker** [stereobooster/jekyll-press#16]
I have full javascript files in specific folders that I would like to ignore. I tried to have excludes be *folder* and several other things following http://www.ruby-doc.org/core-2.0/File.html#method-c-fnmatch

This worked in irb (my result was true) but then it failed in the gem. My only guess is that it's just using the filename to compare, and not the entire file path.

Thanks.

**Comment by stereobooster** [comment]
project is deprecated https://github.com/stereobooster/jekyll-press/issues/35
