### ISSUE TITLE
What if your Website is not in English

### ISSUE THREAD

**Issue by Delaunay** [stereobooster/jekyll-press#21]
Jekyll manage utf-8 character pretty well. Nevertheless, jekyll-press use gems that do not do as well. While I was running `jekyll server` I encountered the following error :

```
/home/jharvard/.gem/ruby/gems/json-1.8.1/lib/json/common.rb:223:in `encode': "\xE2" on US-ASCII (Encoding::InvalidByteSequenceError)
```

The way to fix it was for me to use : `LANG="fr_FR.UTF-8" bundle exec jekyll serve` instead.

is there a better way to fix that ?

PS : I still got an error on a css file but was the bootstrap file so I am guessing it has nothing to do with encoding this time.

**Comment by stereobooster** [comment]
project is deprecated https://github.com/stereobooster/jekyll-press/issues/35
