### ISSUE TITLE
Doesn't compress posts html

### ISSUE THREAD

**Issue by entozoon** [stereobooster/jekyll-press#25]
If you have posts in folders such as 
`/recipes/_posts/post-name.md`
(as is the new way of doing things)

It doesn't compress the html, but it does for `/index.html` and `/recipes/index.html`

**Comment by JamieCressey** [comment]
+1

**Comment by andrew-smart** [comment]
+1

**Comment by jorgt** [comment]
+1

**Comment by asgarli** [comment]
+1

**Comment by dgattey** [comment]
+1

**Comment by ArneGockeln** [comment]
+1

**Comment by stereobooster** [comment]
project is deprecated https://github.com/stereobooster/jekyll-press/issues/35
