### ISSUE TITLE
Minify just CSS and JS (Not HTML)

### ISSUE THREAD

**Issue by Coysh** [stereobooster/jekyll-press#26]
The options are limited. Are there any options to compress just the Javascript and CSS, and keep the HTML clean?

**Comment by rrevanth** [comment]
Hi, seems like dev is not updating,

I actually tried several plugins including this and cannot find a good solution.

I ended up creating rake task for minifying and it is highly customisable.

You can see it at this [gist](https://gist.github.com/rrevanth/9377cb1f1664bf610e38)

**Comment by taxilly** [comment]
You can just add this to your `_config.yml`

```
# Minifier
jekyll-press:
  exclude: '*.html'
```

The wildcard selects all html files and excludes them from the minifier

**Comment by stereobooster** [comment]
project is deprecated https://github.com/stereobooster/jekyll-press/issues/35
