### ISSUE TITLE
should be post processor not pre processor

### ISSUE THREAD

**Issue by JazzMaster** [stereobooster/jekyll-press#33]
There is a glitch here in the sequence of events that causes site text compression when used as-is.

If done properly then there is no need for ruby to cleanup the extra spaces but as-is, we are taking out potential br and paragraph codes as a preprocessor, when in post these would be just extra spaces in the html output. I have a ruby script that removes those and cleans up the html. It doesnt minify however.

--
desc "cleans up empty lines"
task :cleanup do
Dir['_site/**/*.html'].each do |file|
    file_to_strip = IO.readlines(file)
    fout = File.open("temp.html", "w")
    in_code_block = false
    file_to_strip.each do |line|
        if line.include?("<code>") or line.include?("<pre>")
            in_code_block = true
        end
        if (not in_code_block and not line.strip.empty?) or in_code_block
            fout << line
        end
        if line.include?("</code>") or line.include?("</pre>")
            in_code_block = false
        end
    end
    fout.close
    File.rename("temp.html", file)
end
end

**Comment by JazzMaster** [comment]
that didnt work. one sec.

[rakefile.txt](https://github.com/stereobooster/jekyll-press/files/1080011/rakefile.txt)

**Comment by stereobooster** [comment]
project is deprecated https://github.com/stereobooster/jekyll-press/issues/35
