### ISSUE TITLE
Error in HTML and in console

### ISSUE THREAD

**Issue by OliverJAsh** [stereobooster/jekyll-press#4]
In the console I am getting this error from `jekyll`. This only occurs with jekyll_press:

```
parse error occurred while processing: /Users/Oliver/Development/Personal/OliverJAsh/site/css/base.css
details: parse error on value ":not(" (error)
copying initial file
```

I am also getting an error of `Uncaught SyntaxError: Unexpected token ILLEGAL` in the browser console. Something seems to be going wrong in the minification of the HTML here.

My project where I am witnessing this problems [can be found here](https://github.com/OliverJAsh/oliverash.me).

**Comment by stereobooster** [comment]
project is deprecated https://github.com/stereobooster/jekyll-press/issues/35
